### ISSUE TITLE
Joe.ie - Unable to scroll down on any page

### ISSUE THREAD

**Issue by germaloney11** [ryanbr/fanboy-adblock#1274]
Original thread: https://github.com/uBlockOrigin/uAssets/issues/5437

https://www.joe.ie
https://www.joe.ie/life-style/greta-thunberg-666667?fbclid=IwAR2_6cDu7Kfzat2LLLqu8GwRF2_U6htfEdje4rCplEYtWUleosSr0bh2Az4

Describe the issue
Unable to scroll down. Zapping the header seems to fix it.

Screenshot(s)
Versions
Browser/version: Google Chrome - Version 79.0.3945.88 (Official Build) (64-bit)

uBlock Origin v1.23.0

Settings
Notes

**Comment by THEtomaso** [comment]
It's a GDPR issue, where the cookie consent needs to be accepted.

### Problem filters:

* **Fanboy's Annoyance List** / **Fanboy's Cookie List**
```
##.qc-cmp-ui-container
/cmpui-banner.js
||vendorlist.consensu.org^$third-party
```

* **Fanboy's Enhanced Tracking List**
`||quantcast.mgr.consensu.org^$subdocument`

--

### Other problem filters:

* **AdGuard Annoyances filter** @BlazDT
`||consensu.org^$third-party`

* **Dan Pollock's hosts file**
`vendorlist.consensu.org`

* **Frellwit's Swedish Filter** @lassekongo83
`||consensu.org^$third-party,domain=~mirror.co.uk|~sourceforge.net`

* **I don't care about cookies** @kiboke
`quantcast.mgr.consensu.org$domain=~sourceforge.net|~vi.nl`

**Comment by BlazDT** [comment]
Fixed for AdGuard. Hid the cookie dialogue the manual way as only a few seconds there is no scrolling (can only experience on products which do not support #$# rules). Also hid some left-over.

**Comment by krystian3w** [comment]
@majkiIT: `||static.quantcast.mgr.consensu.org^$badfilter`

**Comment by ryanbr** [comment]
I'm not seeing any issues (from a UK IP to test) https://secure.fanboy.co.nz/gif/joeie.gif  There is small delay in displaying the scrollbar, but fixed it self without input

**Comment by THEtomaso** [comment]
Well, as demonstrated plenty of times before, GDPR-related issues are often very region-specific.
I re-tested this particular issue right now, and can confirm that the problem rules are still the ones that I mentioned in my previous post.
The problem does NOT fix itself at my end, but results in a permanantly missing scroll bar!

**Comment by kiboke** [comment]
@THEtomaso thank you, I'll add an exception!
