### ISSUE TITLE
Enchanced tracking list blocks images on some localized Googles

### ISSUE THREAD

**Issue by wooque** [ryanbr/fanboy-adblock#42]
On google.rs, google.es, probably on some more, images are blocked as seen on screenshot:
![screenshot_2016-10-21_12-20-08](https://cloud.githubusercontent.com/assets/1936195/19595262/45cc8672-9789-11e6-8c88-e9a21d031668.png)
uBlock Origin log says it because of Fanboy's Enhanced Tracking List rule:
![screenshot_2016-10-21_12-23-23](https://cloud.githubusercontent.com/assets/1936195/19595270/51bda3da-9789-11e6-8be1-b8b545df3548.png)

**Comment by ryanbr** [comment]
https://github.com/ryanbr/fanboy-adblock/commit/32799a1eda203de0146fa575b9afa222a58f6681

**Comment by wooque** [comment]
Fixed

**Comment by betterwebleon** [comment]
It seems that [small icons](http://pad3.whstatic.com/images/thumb/e/eb/Use-Google-Translate-Step-4.jpg/aid1220411-728px-Use-Google-Translate-Step-4.jpg) ("_Handwriting_", "_Listen_", etc.) are sometimes still not visible on various `translate.google` subdomains.

The following exception rule seems to work for me (it's a bit broader from the existing one):
`@@||ssl.gstatic.com/*$image,third-party`

**Comment by ryanbr** [comment]
Looks fine here.
